ALTER TABLE events
ADD COLUMN user_id INT UNSIGNED NULL DEFAULT NULL AFTER city_id,
ADD COLUMN view_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER user_id,
ADD COLUMN is_favourite TINYINT(1) NOT NULL DEFAULT 0 AFTER view_count;

ALTER TABLE event_likes
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE event_favourites
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE events
MODIFY COLUMN view_count INT UNSIGNED NOT NULL DEFAULT 0,
MODIFY COLUMN is_favourite TINYINT(1) NOT NULL DEFAULT 0;
